import { Component, signal, inject, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { ChangeDetectionStrategy } from '@angular/core';
import { DecimalPipe } from '@angular/common';

@Component({
  selector: 'app-cashier-qr-code',
  imports: [DecimalPipe],
  templateUrl: './cashier-qr-code.html',
  styleUrl: './cashier-qr-code.css',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class CashierQRCodeComponent implements OnInit {
  private readonly router = inject(Router);

  protected readonly amount = signal<string>('0.00');
  protected readonly paymentId = signal<string>('');
  protected readonly paymentUrl = signal<string>('');
  protected readonly qrCodeData = signal<string>('');

  ngOnInit(): void {
    const navigation = this.router.getCurrentNavigation();
    const state = navigation?.extras?.state || history.state;

    if (state?.['amount']) {
      this.amount.set(state['amount']);
      this.generateQRData(state['amount']);
    } else {
      // If no amount, redirect back to amount page
      this.router.navigate(['/cashier/amount']);
    }
  }

  private generateQRData(amount: string): void {
    // Generate a unique payment ID
    // In production, this would be generated by the backend
    const paymentId = 'PAY-' + Date.now() + '-' + Math.random().toString(36).substring(7);
    this.paymentId.set(paymentId);

    // Generate the payment URL that customers will use
    const baseUrl = window.location.origin;
    const paymentUrl = `${baseUrl}/customer/payment/${paymentId}`;
    this.paymentUrl.set(paymentUrl);

    // The QR code should encode the payment URL
    // When customers scan it, they'll be directed to the payment page
    this.qrCodeData.set(paymentUrl);

    // TODO: In production, register this payment with the backend
    // The backend should store: paymentId, amount, merchantId, timestamp, status
    console.log('Payment created:');
    console.log('- Payment ID:', paymentId);
    console.log('- Amount:', amount);
    console.log('- Payment URL:', paymentUrl);
    console.log('- QR Code Data:', paymentUrl);
  }

  protected goBack(): void {
    this.router.navigate(['/cashier/amount'], {
      queryParams: { amount: this.amount() }
    });
  }

  protected newTransaction(): void {
    this.router.navigate(['/cashier/amount']);
  }

  protected logout(): void {
    this.router.navigate(['/cashier/login']);
  }
}